config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  scope "/admin" do
    resources :users do
      member do
        get :icalendar
      end
    end
  end

  get "sitemap" => "sitemap#show", format: :xml, as: :sitemap

  get 'invite' => 'projects#invite' 
  post 'invite' => 'projects#invite_do' 
  get 'accepter' => 'projects#accepter' 

  post 'todos/:id/close' => 'todos#close'
  post 'todos/:id/reopen' => 'todos#reopen'

  get 'projects/:id/save_as_template' => 'projects#save_as_template'
  post 'projects/:id/save_as_template' => 'projects#save_as_template_post'

  get 'documents/index'
  delete 'documents/purge'

  get "agenda/index"

  get "show_attrs" => "tables#show_attrs" 

  resources :accounts, only: %i[ edit update ] do
    member do
      get :suppression_compte
      post :suppression_compte_do
    end
  end
  resources :comments, only: %i[ index create ]
  resources :templates
  resources :logs
  resources :todolists, except: :index
  resources :participants, only: %i[ edit update ]
  resources :todos, except: %i[ show ]
  resources :projects
  resources :tables
  resources :fields, only: %i[ edit update create destroy ]
  resources :mail_logs, only: %i[ index ]

  get 'tables/:id/fill' => 'tables#fill', as: :fill
  post 'tables/:id/fill' => 'tables#fill_do', as: :fill_do
  get 'tables/:id/link' => 'tables#link', as: :link
  post 'tables/:id/link' => 'tables#link_do', as: :link_do

  delete 'tables/:id/delete_record' => 'tables#delete_record', as: :delete_record

  get 'about', to: 'pages#about', as: :about
  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  get 'audits/index'

  get '/service-worker.js' => "service_worker#service_worker"
  get '/manifest.json' => "service_worker#manifest"

  namespace :api, defaults: {format: 'json'} do 
    namespace :v1 do 
        resources :todos
    end 
  end

  root 'projects#index'
end

app/views/templates/_form.html.erb
<%= form_for(@template) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nom" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :project %><br>
    <%= f.text_field :project, size:'97' %>
  </div>
  <div class="field">
    <%= f.label :participants %><br>
    <%= f.text_area :participants, size:'130x5' %>
  </div>
  <div class="field">
    <%= f.label :todolists %><br>
    <%= f.text_area :todolists, size:'130x10' %>
  </div>
  <div class="field">
    <%= f.label :todos %><br>
    <%= f.text_area :todos, size:'130x10' %>
  </div>
  <div class="actions">
    <%= f.submit "Enregistrer", class:'btn btn-primary btn-outline' %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<h1>Modification modèle</h1>

<%= render 'form' %>

<%= link_to 'Retour', templates_path %>

app/views/templates/index.html.erb
<h1 class="mb-6">Modèles</h1>

<div class="overflow-x-auto">
  <table class="table table-zebra">
    <thead>
      <tr>
        <th>Nom</th>
        <th>Projet source</th>
        <th>Description</th>
        <th>Créé le</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @templates.each do |template| %>
        <% th = JSON.parse(template.project).to_h %> 
        <tr class="hover">
          <td><b><%= link_to template.name.humanize, template, class:'link' %></b></td>
          <td><%= th["name"] %></td>
          <td><%= th["description"] %></td>
          <td><%= l(template.created_at) %></td>
          <td><%= button_to '[X]', template, method: :delete, form: { data: {'turbo-confirm': 'Certain(e) ?' } } %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
    <tr>
      <th colspan=5></th>
    </tr>
    </tfoot>
  </table>
</div>

app/views/templates/new.html.erb
<h1>New template</h1>

<%= render 'form' %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p class="text-lg mb-4">
  <strong>Nom:</strong>
  <%= page_title! @template.name %>
</p>

<p class="text-lg mb-4">
  <strong>Project:</strong>
  <%= @template.project %>
</p>

<p class="text-lg mb-4">
  <strong>Participants:</strong>
  <%= @template.participants %>
</p>

<p class="text-lg mb-4">
  <strong>Todolists:</strong>
  <%= @template.todolists %>
</p>

<p class="text-lg mb-4">
  <strong>Todos:</strong>
  <%= @template.todos %>
</p>

<%= link_to 'Modifier', edit_template_path(@template) %> |
<%= link_to 'Retour', templates_path %>