config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  scope "/admin" do
    resources :users do
      member do
        get :icalendar
      end
    end
  end

  get "sitemap" => "sitemap#show", format: :xml, as: :sitemap

  get 'invite' => 'projects#invite' 
  post 'invite' => 'projects#invite_do' 
  get 'accepter' => 'projects#accepter' 

  post 'todos/:id/close' => 'todos#close'
  post 'todos/:id/reopen' => 'todos#reopen'

  get 'projects/:id/save_as_template' => 'projects#save_as_template'
  post 'projects/:id/save_as_template' => 'projects#save_as_template_post'

  get 'documents/index'
  delete 'documents/purge'

  get "agenda/index"

  get "show_attrs" => "tables#show_attrs" 

  resources :accounts, only: %i[ edit update ] do
    member do
      get :suppression_compte
      post :suppression_compte_do
    end
  end
  resources :comments, only: %i[ index create ]
  resources :templates
  resources :logs
  resources :todolists, except: :index
  resources :participants, only: %i[ edit update ]
  resources :todos, except: %i[ show ]
  resources :projects
  resources :tables
  resources :fields, only: %i[ edit update create destroy ]
  resources :mail_logs, only: %i[ index ]

  get 'tables/:id/fill' => 'tables#fill', as: :fill
  post 'tables/:id/fill' => 'tables#fill_do', as: :fill_do
  get 'tables/:id/link' => 'tables#link', as: :link
  post 'tables/:id/link' => 'tables#link_do', as: :link_do

  delete 'tables/:id/delete_record' => 'tables#delete_record', as: :delete_record

  get 'about', to: 'pages#about', as: :about
  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  get 'audits/index'

  get '/service-worker.js' => "service_worker#service_worker"
  get '/manifest.json' => "service_worker#manifest"

  namespace :api, defaults: {format: 'json'} do 
    namespace :v1 do 
        resources :todos
    end 
  end

  root 'projects#index'
end

app/models/participant.rb
class Participant < ApplicationRecord
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  audited


  belongs_to :project
  belongs_to :user

  validates :user_id, uniqueness: { scope: :project_id }

  scope :notification_subcribers, -> {where(want_notification:true)} 

  private

  def slug_candidates
    [SecureRandom.uuid]
  end

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: %i[ edit update ]
  before_action :user_authorized?

  # GET /participants/1/edit
  def edit; end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant.user, notice: 'Modification enregistrée...' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_participant
    @participant = Participant.find_by(slug: params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def participant_params
    params.require(:participant).permit(:project_id, :user_id, :want_notification, :want_dailynewsletter,
                                        :want_weeklynewsletter, :client)
  end

  def user_authorized?
    authorize @participant
  end
end

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :project_id %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>

  <div class="field">
    <%= f.check_box :want_notification %>
    <%= f.label "Notification" %><br>
    <i>Recevoir une notification par courriel après chaque changement dans le projet ?</i>
  </div>

  <div class="field">
    <%= f.check_box :want_dailynewsletter %>
    <%= f.label "daily newsletter" %><br>
    <i>Recevoir un résumé journalier des changements ?</i>
  </div>
  
  <div class="field">
    <%= f.check_box :want_weeklynewsletter %>
    <%= f.label "weekly newsletter" %><br>
    <i>Recevoir un résumé hebdomadaire des changements ?</i>
  </div>
  <br>

  <div class="actions">
    <%= f.submit 'Enregistrer', class: 'btn btn-primary btn-outline' %>
  </div>
<% end %>

app/views/participants/_participant.html.erb
<tr>
  <td><span style="background-color:<%= participant.project.color %>;padding-left:5px;margin-right:5px;"></span></td>
  <td>
    <%= participant.project.name %>
  </td>
  <td>
    <%= image_tag "yes.png" if participant.want_notification %>
  </td>
  <td>
    <%= image_tag "yes.png" if participant.want_dailynewsletter %>
  </td>
  <td>
    <%= image_tag "yes.png" if participant.want_weeklynewsletter %>
  </td>
  <td>
    <%= link_to "Modifier", edit_participant_path(participant) %>
  </td>
</tr>

app/views/participants/edit.html.erb
<h1>Vos abonnements</h1>
<div class="mb-8 pl-2" style="border-left: 7px solid <%= @participant.project.color %>">
  <h2>Projet: <%= @participant.project.name %></h2>
</div>

<%= render 'form' %>

<%= link_to 'Retour', user_path(@participant.user.slug) %>