config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  scope "/admin" do
    resources :users do
      member do
        get :icalendar
      end
    end
  end

  get "sitemap" => "sitemap#show", format: :xml, as: :sitemap

  get 'invite' => 'projects#invite' 
  post 'invite' => 'projects#invite_do' 
  get 'accepter' => 'projects#accepter' 

  post 'todos/:id/close' => 'todos#close'
  post 'todos/:id/reopen' => 'todos#reopen'

  get 'projects/:id/save_as_template' => 'projects#save_as_template'
  post 'projects/:id/save_as_template' => 'projects#save_as_template_post'

  get 'documents/index'
  delete 'documents/purge'

  get "agenda/index"

  get "show_attrs" => "tables#show_attrs" 

  resources :accounts, only: %i[ edit update ] do
    member do
      get :suppression_compte
      post :suppression_compte_do
    end
  end
  resources :comments, only: %i[ index create ]
  resources :templates
  resources :logs
  resources :todolists, except: :index
  resources :participants, only: %i[ edit update ]
  resources :todos, except: %i[ show ]
  resources :projects
  resources :tables
  resources :fields, only: %i[ edit update create destroy ]
  resources :mail_logs, only: %i[ index ]

  get 'tables/:id/fill' => 'tables#fill', as: :fill
  post 'tables/:id/fill' => 'tables#fill_do', as: :fill_do
  get 'tables/:id/link' => 'tables#link', as: :link
  post 'tables/:id/link' => 'tables#link_do', as: :link_do

  delete 'tables/:id/delete_record' => 'tables#delete_record', as: :delete_record

  get 'about', to: 'pages#about', as: :about
  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  get 'audits/index'

  get '/service-worker.js' => "service_worker#service_worker"
  get '/manifest.json' => "service_worker#manifest"

  namespace :api, defaults: {format: 'json'} do 
    namespace :v1 do 
        resources :todos
    end 
  end

  root 'projects#index'
end

app/models/project.rb
class Project < ApplicationRecord
  include LogConcern
  extend SimpleCalendar

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  audited

  acts_as_taggable
    
    #has_calendar :attribute => :created_at  

  belongs_to :account

  has_many :todolists, dependent: :destroy
  has_many :todos, through: :todolists
  has_many :comments, through: :todos
  has_many :participants, dependent: :destroy
  has_many :users, through: :participants
  has_many :logs, dependent: :destroy

  validates :name, presence: true
  validates :workflow, presence: true

  default_scope {order('projects.name')}

  def pct_avancee 
    unless self.todos.count.zero?
      ((self.todos.done.count * 100)  / self.todos.count)
    else
      0
    end
  end

  def bar_avancee
    "<span id='progress'>#{'.' * (self.pct_avancee / 10)}</span><span id='progress_done'>#{'.' * (10 - (self.pct_avancee / 10))}</span>"
    end        

  def last_update
    if self.logs.any?
      self.logs.maximum(:created_at)
    else
      Date.today
    end
  end

  def workflow?
    self.workflow == 1
  end

  def current_todolist
    lists = self.todolists.reorder(:row).select{|l| !l.done? }
    return lists.first
  end

  def daily_logs
    self.logs.where(created_at: 1.days.ago.to_date..Date.today).reorder(:created_at)
  end

  def weekly_logs
    self.logs.where(created_at: 7.days.ago.to_date..Date.today).reorder(:created_at)
  end

  private

  def slug_candidates
    [SecureRandom.uuid]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project,
                only: %i[show edit update destroy save_as_template save_as_template_post invite ]
  before_action :user_authorized?, except: %i[ show edit update destroy invite invite_do ]

  # skip_before_action :authorize, only: :accepter

  # GET /projects
  # GET /projects.json
  def index
    @user = current_user
    @projects = @user.projects
    @logs = @user.logs.except_comments.limit(5)
    @comments = @user.comments.limit(5)
    @tags = @projects.tag_counts_on(:tags)

    unless params[:search].blank?
      @projects = @projects.where('name ILIKE ? OR description ILIKE ? OR memo ILIKE ?', "%#{params[:search]}%",
                                  "%#{params[:search]}%", "%#{params[:search]}%")
      @logs = @logs.where('logs.description ILIKE ?', "%#{params[:search]}%")
      @comments = @comments.where('comments.texte ILIKE ?', "%#{params[:search]}%")
    end

    unless params[:tag].blank?
      @projects = @projects.tagged_with(params[:tag])
      @logs = @logs.where(project_id: @projects.pluck(:id))
      @comments = @user.comments.joins(:project).where('projects.id in(?)', @projects.pluck(:id))
    end

    @projects = @projects.uniq
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    authorize @project

    session[:show_only_undone] ||= "no"
    @logs = @project.logs.except_comments.limit(5)
    @comments = @project.comments.limit(5)
    @todolists = if @project.workflow == 1
                   @project.todolists.order(:row)
                 else
                   @project.todolists.order(:name)
                 end

    unless params[:search].blank?
      @todolists = @todolists.joins(:todos)
                              .where('todolists.name ILIKE :search OR todos.name ILIKE :search', {search: "%#{params[:search]}%"})
    end

    params[:show_only_undone] ||= session[:show_only_undone]

    if params[:show_only_undone] == "yes"
      @todolists = @todolists.joins(:todos).where('todos.done IS FALSE')
    end

    session[:show_only_undone] = params[:show_only_undone]

    @todolists = @todolists.uniq
  end

  # GET /projects/new
  def new
    @project = Project.new
    @user = current_user
    @account = @user.account
    @templates = @account.templates
    @participants = @account.users
    @tables = @account.tables
  end

  # GET /projects/1/edit
  def edit
    authorize @project

    @account = current_user.account
    @templates = @account.templates
    @participants = @account.users
    @tables = @account.tables
  end

  # POST /projects
  # POST /projects.json
  def create
    if params[:template_id].blank?
      @project = Project.new(project_params)
      @project.account_id = current_user.account_id
      @project.save
      @project.participants.create(user_id: current_user.id)
      redirect_to @project, notice: "Le projet '#{@project.name}' vient d'être ajouté"
    else
      CreateProjetFromTemplate.new(params[:template_id], project_params[:name]).call 
      redirect_to projects_path, notice: "Le projet '#{ project_params[:name] }' vient d'être créé à partir d'un modèle"
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    authorize @project

    respond_to do |format|
      @project.attributes = project_params
      @project.log_changes(:edit, current_user.id)
      if @project.save(validates: false)
        if params[:participants]
          # logger.debug "DEBUG params_participants:#{params[:participants].inspect} class:#{params[:participants].class}"
          participants = @project.participants.pluck(:user_id).collect { |i| i.to_s }

          # ajout de participants ?
          diff = params[:participants] - participants
          diff.each do |participant_ajout_id|
            @project.participants.create(user_id: participant_ajout_id)
            Log.create(project_id: @project.id, user_id: current_user.id, action_id: 1,
                       description: "ajouté le participant <b>#{User.find(participant_ajout_id).name}</b> au projet <a href='/projects/#{@project.id}'>#{@project.name}</a>")
          end

          # suppression de participants ?
          diff = participants - params[:participants]
          diff.each do |participant_supprime_id|
            @project.participants.find_by(user_id: participant_supprime_id).destroy
            Log.create(project_id: @project.id, user_id: current_user.id, action_id: 1,
                       description: "enlevé le participant <b>#{User.find(participant_supprime_id).name}</b> au projet <a href='/projects/#{@project.id}'>#{@project.name}</a>")
          end
        end
        format.html { redirect_to @project, notice: 'Modifications projet enregistrées' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    authorize @project

    # @project.log_changes(:delete, current_user.id)
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_path, notice: "Projet supprimé" }
      format.json { head :no_content }
    end
  end

  def save_as_template; end

  def save_as_template_post
    if params[:name].blank?
      redirect_to action: :save_as_template, notice: 'Merci de donner un nom à ce modèle !'
      nil
    else
      # export projet + todolist + participants + todo to json files
      to_except = %w[id created_at updated_at]
      project_js = @project.attributes.except(*to_except).to_json
      participants_js = @project.participants.to_json
      todolists_js = @project.todolists.to_json
      todos_js = @project.todos.to_json
      account_id = current_user.account_id
      Template.create(account_id:, name: params[:name], project: project_js, participants: participants_js,
                      todolists: todolists_js, todos: todos_js)
      redirect_to @project, notice: "Modèle '#{params[:name]}' créé avec succès"
    end
  end

  def new_from_template; end

  def invite
    authorize @project

    @users = current_user.account.users
                          .where.not(id: current_user.id )
                          .where.not(id: @project.participants.pluck(:user_id) )
  end

  # Ajout 
  def invite_do
    @project = Project.find_by(slug: params[:id])
    authorize @project

    participant = @project.participants.create(user: User.find(params[:user_id]), client: false)

    Log.create(project_id: @project.id, user_id: current_user.id, action_id: 1,
              description: "invité le participant <b>#{participant.user.name}</b> au projet '<a href='/projects/#{@project.id}'>#{@project.name}</a>'")

    redirect_to invite_path(id:@project.slug), notice: "Participant ajouté"
    
    # if params[:courriel].blank?
    #   redirect_to invite_path(id:@project.slug), alert: 'Veuillez entrer une adresse'
    # elsif params[:client]
    #   mail = params[:courriel]
    #   user = User.find_by(email: mail)
    #   if user
    #     redirect_to invite_path(id:@project.slug), alert: 'Participant déjà ajouté'
    #   else
    #     participant = @project.participants.new(user: User.find_by(email: params[:courriel]), client: false)
    #     username = mail.split('@').first
    #     pass = random_password
    #     user = User.create(name: username, username:, email: mail, password: pass, password_confirmation: pass,
    #                        account: current_user.account)
    #   end
    #   @project.participants.create(user_id: user.id, client: true)
    #   redirect_to projects_path, notice: 'Invitation envoyée au client'

    # # chercher le client dans user
    # # si n'existe pas, on le crée
    # # on l'ajoute comme participant au projet en lecture seule
    # else
    #   participant = @project.participants.new(user: User.find_by(email: params[:courriel]), client: false)
    #   if participant.valid?
    #     participant.save
    #     Notifier.invite(@project, current_user, params[:courriel]).deliver_now
    #     # ajoute à l'activité
    #     Log.create(project_id: @project.id, user_id: current_user.id, action_id: 1,
    #               description: "invité le participant <b>#{params[:courriel]}</b> au projet '<a href='/projects/#{@project.id}'>#{@project.name}</a>'")
    #     redirect_to projects_path, notice: 'Invitation envoyée'
    #   else
    #     redirect_to invite_path(id:@project.slug), alert: 'Participant déjà ajouté'
    #   end
    # end
  end

  def accepter
    mail_invite = params[:q]
    project = Project.friendly.find(params[:p])
    user_qui_invite = User.find(params[:u])

    unless User.find_by(email:mail_invite)
      # username = partie avant le @ du mail
      username = mail_invite.split('@').first
      # créer un mot de passe
      pass = random_password
      # créer un user
      user = User.create(name:username, username:username, email:mail_invite, password:pass, password_confirmation:pass,
                          account_id:user_qui_invite.account_id)
      # notifier par mail du mot de passe
      # mailer_response = Notifier.welcome(user, pass, project).deliver_now
      # MailLog.create(account_id: current_user.account.id, message_id:mailer_response.message_id, to:user.email, subject: "Bienvenue.")
      flash[:notice] = "Vos informations de connexion viennent d'être envoyées sur #{mail_invite} ..."
    else
      user = User.find_by(email:mail_invite)
    end

    # ajouter le user comme un participant au projet
    unless project.participants.where(user_id:user.id).any?
      project.participants.create(user_id:user.id)

      # ajoute à l'activité
      Log.create(project_id:project.id, user_id:user_qui_invite.id, action_id:1,
                description:"ajouté le participant <b>#{username}</b> au projet '<a href='/projects/#{project.id}'>#{project.name}</a>'")

app/views/projects/edit.html.erb
<h1 class="mb-6">Modification projet</h1>

<%= render 'form' %>

<%= link_to "Enregistrer ce projet comme modèle", 'save_as_template', class:'link' %> |
<%= link_to 'Annuler', @project, class:'link' %>
<%= button_to "Supprimer ce projet",
              @project, 
              method: :delete,
              form: { data: {'turbo-confirm': "--- ATTENTION ! ---\n\n Vous êtes sur le point de supprimer définitivement ce projet ! Cette action est IRRÉVERSSIBLE !" } },
              class:"mb-6" %>

app/views/projects/index.html.erb
<h1 class="mb-6">
  Projets
  <% if policy(Project).new? %>
    <%= link_to new_project_path, title:'Ajouter un projet' do %>
      <div class="badge badge-accent badge-outline rounded badge-lg pb-0.5 shadow">+</div>
    <% end %>
  <% end %>
</h1>

<% if @tags.any? %>
  <div class="mb-4">
    <span>
      Tags :
      <% tag_cloud(@tags, ['badge-sm', '', 'badge-md', 'badge-lg']) do |tag, css_class| %>
        <%= link_to(tag.name, projects_path(tag:tag.name), class: 'badge badge-outline ' + css_class) %>
      <% end %>
    <span>
  </div>
<% end %>

<% if @projects.any? %>
  <div class="overflow-x-auto">
    <table class="table table-normal">
      <thead>
        <tr class="text-accent">
          <td>Nom / Description</td>
          <th>Échéance</th>
          <th>Charge</th>
          <th>Progression</th>
          <th>Phase en cours</th>
          <th>Participants</th>
          <th>MÀJ</th>
        </tr>
      </thead>

      <tbody>
        <% @projects.each do |project| %>
          <tr class="hover">
            <td class="mb-8 pl-2" style="border-left: 7px solid <%= project.color %>">
              <%= link_to project.name.humanize, project, class: 'text-lg text-primary' %>
              <br>
              <i><small><%= truncate(project.description, length: 100) %></small></i>
            </td>
            <td><%= l(project.duedate) if project.duedate %></td>
            <td>
              <%= number_with_precision(project.todos.sum(:charge_est), precision: 2) %> j
              / <%= number_with_precision(project.todos.sum(:charge_reelle), precision: 2) %> j
            </td>
            <td>
              <% unless project.todos.count.zero? %>
                <progress class="progress progress-success w-56" value=<%= project.pct_avancee %> max="100"></progress>
              <% end %>
            </td> 
            <td>
              <% if project.workflow? and project.current_todolist %>
                <small><%= truncate(project.current_todolist.name, length: 15) %></small>  
              <% end %>
            </td>
            <td>
              <div class="flex">
                <%= link_to users_path(project_id: project.slug) do %>
                  <div class="avatar-group -space-x-6">
                    <% project.users.each do |user| %>
                      <div class="avatar placeholder">
                        <% if user.avatar.attached? %>
                          <div class="w-8 rounded-full !bg-slate-500">
                            <%= image_tag(user.avatar, size:'15x15', alt:'', class:"mini_avatar inline") %>
                          </div>
                        <% else %>
                          <div class="bg-primary-focus text-neutral-content rounded-full w-8">
                            <span class="text-primary-content"><%= user.username.first.humanize %></span>
                          </div>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                <% end %>
                <%= link_to invite_path(id:project.slug), title:'Inviter un nouveau participant', class:'ml-2' do %>
                  <div class="badge badge-accent badge-outline rounded badge-lg mt-2 pb-0.5 shadow">+</div>
                <% end %>
              </div>
            </td>
            <td style="color:lightgrey"><%= "Il y a #{time_ago_in_words(project.last_update)}" if project.logs.any? %></td>
          </tr>
          <tr />  
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <% unless params[:search].blank? %>
    <i>Aucun projet à afficher...</i>
  <% else %>
    <p>
      Vous ne participez à aucun projet actuellement.
      <br>
      Cliquez sur
      <%= link_to new_project_path do %>
        <span class="badge badge-accent badge-outline rounded badge-lg pb-0.5 shadow">+</span>
      <% end %>
      pour créer un nouveau projet.
    </p>
  <% end %>
  <br>
<% end %>


<% if @logs.any? %>
  <hr class="style-two">
  <h2 class="mt-6">
    Activité
  </h2>
  <%= render partial:'logs/log', collection:@logs, day:0, user_id:0 %>
  <br>
  <% if @logs.count > 5 %>  
    <small><i>Liste des 5 derniers changements. <%= link_to "Afficher tout", logs_path, class:"link" %></i></small>
    <br>
  <% end %>
  <br>
<% end %>


<% if @comments.any? %>
  <hr class="style-two">
  <h2 class="mt-6">
    Discussions
  </h2>
  <%= render partial:'comments/commentfull', collection:@comments, as: :comment, comment_day:0, user_id:0  %>
  <br>
  <% if @comments.count >= 5 %>
    <small><i>Liste des 5 derniers commentaires. <%= link_to "Afficher tout", comments_path %></i></small>
    <br>
  <% end %>
  <br>
<% end %>

app/views/projects/new.html.erb
<h1 class="mb-6">Nouveau projet</h1>

<%= render 'form' %>

app/views/projects/save_as_template.html.erb
<h1 class="flex items-center mb-6">
  <span class="pl-2" style="border-left: 7px solid <%= @project.color %>"><%= @project.name %></span>
</h1>

<h2>Enregistrer ce projet comme modèle</h2>


<p class="mb-4 italic">
  Permet la création rapide de nouveaux projets à partir de ce modèle de projet
</i>

<%= form_tag do %>
  <%= label_tag :name, "Nom du nouveau modèle" %>
  <br>
  <%= text_field_tag :name, {}, { class:'input input-bordered' } %>

  <br>
  <%= submit_tag "Enregistrer", class: 'btn btn-primary btn-outline mt-8' %>
<% end %>

app/views/projects/show.html+phone.erb
<div class="pl-2" style="border-left: 7px solid <%= @project.color %>">
  <div class="flex items-center">
    <h2 class="text-primary"><%= page_title! @project.name.humanize %></h2>
    <%= link_to "Modifier", edit_project_path(@project), class: 'ml-3 text-base-content hover:text-black' %> 
  </div>
  <% unless @project.description.blank? %>
    <i><%= @project.description %></i>
  <% end %>

  <% if @project.tag_list.any? %>
    <div class="flex items-center overflow-x-auto gap-1 py-4">
      <% tag_cloud(@project.tags, ['badge-sm', '', 'badge-md', 'badge-lg']) do |tag, css_class| %>
        <%= link_to(tag.name, project_path(tag:tag.name), class: 'badge badge-outline text-base-content break-keep whitespace-nowrap ' + css_class ) %>
      <% end %>
    </div>
  <% end %>

  <% if @project.workflow? and @project.current_todolist %>
    <br>
    <%= @project.current_todolist.name %>
  <% end %>

  <% if @project.duedate %>
    <br>
    Échéance :
    <strong><%= l(@project.duedate) %></strong>
  <% end %>

  <% if @project.todos %>
    <br>
    Charge :
    <strong><%= number_with_precision(@project.todos.sum(:charge_est), precision: 2) %></strong>
    / <strong><%= number_with_precision(@project.todos.sum(:charge_reelle), precision: 2) %></strong> jours
  <% end %>

  <br>
  Progression
  <br>
  <progress class="progress progress-success !w-56" value=<%= @project.pct_avancee %> max="100"></progress>
  <small>(<%= @project.pct_avancee %>%)</small>
</div>

<div class="mt-2">
  <% if @project.todolists.any? %>
    <% if @project.todos.any? %>
      <div class="btn-group w-full px-2 mt-6">
        <%= link_to "Tout (#{@project.todos.count})", url_for(params.permit(:tag).merge(show_only_undone: "no")), class: "flex-1 btn btn-sm btn-outline #{ params[:show_only_undone] == 'no' ? 'btn-active' : '' }" %>
        <%= link_to "Reste à faire (#{@project.todos.done.count})", url_for(params.permit(:tag).merge(show_only_undone: "yes")), class: "flex-1 btn btn-sm btn-outline #{ params[:show_only_undone] == 'yes' ? 'btn-active' : '' }" %>
      </div>
    <% end %>
  <% else %>
    <small>
      <i>
        Il n'y a aucune liste pour l'instant...
        <br><br>
        Ces listes de choses à faire (Todo List) ou phases séquentielles (Mode linéaire) servent à découper un projet en tranches ou par thématique. 
        <br>
        Ex: Préparation / Travaux / Réception ou Début / Milieu / Fin (Mode Libre) ou Prospection => Evaluation => Devis => Commande => Livraison => Facturation (Mode Linéaire)
        <br><br>
        Cliquez sur 
        <%= link_to new_todolist_path(id: @project.slug), title: 'Ajouter une Todo List/Phase' do %>
          <div class="badge badge-accent badge-outline rounded badge-lg pb-0.5 shadow">+</div>
        <% end %> 
        pour saisir le nom de votre première liste.
      </i>
    </small>
  <% end %>
</div>


<% unless @project.memo.blank? %>
  &nbsp;&nbsp;<i><%= @project.memo %></i>
<% end %>
<br>

<%= render partial: 'todolists/todolist', collection:@todolists, as: :todolist %>

<% if @logs.any? %>
  <br>
  <h2 class="mt-4">
    Activité
  </h2>
  <table id="logs">
    <%= render partial:'logs/log', collection: @logs, :day => 0 %>
  </table>
  <br>
  <% if @logs.count > 5 %>
    <small>
      <i>Liste des 5 derniers changements <%= link_to "Afficher tout", logs_path(project_id:@project.id), class:"link" %></i>
    </small>
    <br>
  <% end %>
<% end %>

<% if @comments.any? %>
  <br>
  <h2 class="mt-4">
    Discussions
  </h2>
  <%= render partial:'comments/commentfull', collection:@comments, as: :comment, day:0  %>
  <br>
  <% if @project.comments.count > 5 %>
    <small><i>Liste des 5 derniers commentaires <%= link_to "Afficher tout", comments_path(project_id:@project.id) %></i></small>
    <br>
  <% end %>
<% end %>

app/views/projects/show.html.erb
<div class="mb-8 pl-2" style="border-left: 7px solid <%= @project.color %>">
  <div class="flex items-center">
    <h2 class="text-primary"><%= page_title! @project.name.humanize %></h2>
    <%= link_to "Modifier", edit_project_path(@project), class: 'ml-3 text-secondary' %> 
  </div>
  <% unless @project.description.blank? %>
    <i><%= @project.description %></i>
  <% end %>
</div>

<% unless @project.pct_avancee.zero? %>
  <span>
    Progression : 
    <progress class="progress progress-success !w-56" value=<%= @project.pct_avancee %> max="100"></progress>
    <small>(<%= @project.pct_avancee %>%)</small>
  </span>
<% end %>

<% if @project.workflow? and @project.current_todolist %>
  <span>| Phase en cours : <%= @project.current_todolist.name %></span>
<% end %>

<% if @project.duedate %>
  <span>| Échéance :<strong><%= l(@project.duedate) %></strong></span>
<% end %>

<% if @project.todos %>
  <span>
    | Charge :<strong><%= number_with_precision(@project.todos.sum(:charge_est), precision: 2) %></strong>
    / <strong><%= number_with_precision(@project.todos.sum(:charge_reelle), precision: 2) %></strong> jours
  </span>
<% end %>

<% if @project.tag_list.any? %>
  <span>
  | Tags :
    <% tag_cloud(@project.tags, ['badge-sm', '', 'badge-md', 'badge-lg']) do |tag, css_class| %>
      <%= link_to(tag.name, projects_path(tag:tag.name), class: 'badge badge-outline ' + css_class) %>
    <% end %>
  </span>
<% end %>

<div class="mt-2">
  <% if @project.todolists.any? %>
    <% if @project.todos.any? %>
      <%= form_tag project_path, method: :get, class:'mb-2' do %>
        <span>
          Afficher :
          <%= radio_button_tag :show_only_undone, "no", params[:show_only_undone] == "no", { onchange: "this.form.submit();", class: 'radio radio-accent radio-sm' } %> Tout
          <%= radio_button_tag :show_only_undone, "yes", params[:show_only_undone] == "yes", { onchange: "this.form.submit();", class: 'radio radio-accent radio-sm ml-4' } %> Reste à faire
        </span>
      <% end %>
    <% end %>
  <% else %>
    <small>
      <i>
        Il n'y a aucune liste pour l'instant...
        <br><br>
        Ces listes de choses à faire (Todo List) ou phases séquentielles (Mode linéaire) servent à découper un projet en tranches ou par thématique. 
        <br>
        Ex: Préparation / Travaux / Réception ou Début / Milieu / Fin (Mode Libre) ou Prospection => Evaluation => Devis => Commande => Livraison => Facturation (Mode Linéaire)
        <br><br>
        Cliquez sur 
        <%= link_to new_todolist_path(id: @project.slug), title: 'Ajouter une Todo List/Phase' do %>
          <div class="badge badge-accent badge-outline rounded badge-lg pb-0.5 shadow">+</div>
        <% end %> 
        pour saisir le nom de votre première liste.
      </i>
    </small>
  <% end %>
</div>


<% unless @project.memo.blank? %>
  &nbsp;&nbsp;<i><%= @project.memo %></i>
<% end %>
<br>

<div class="overflow-x-auto">
  <table class="table table-normal">
    <thead>
      <td><%= @project.workflow? ? 'Phases' : 'Todo List' %></td>
      <th>Tâches <%= params[:show_only_undone] == "yes" ? "(à faire)" : "(toutes)" %></th>
      <th>Réalisation</th>
      <th>Échéance</th>
      <th>Charge est.</th>
      <th>Réelle</th>
      <th>MÀJ</th>
      <th>Écart</th>
    </thead>
    <tbody>
      <%= render partial: 'todolists/todolist', collection: @todolists %>
    </tbody>
    <tfoot>
      <tr>
        <th>
          <% if current_user.admin? %>
            <%= link_to new_todolist_path(id: @project.slug), title: 'Ajouter une Todo List/Phase' do %>
              <div class="badge badge-accent badge-outline rounded badge-lg pb-0.5 shadow">+</div>
            <% end %>
          <% end %>
        </th>
        <td colspan=7></td>
      </tr>
    </tfoot>  
  </table>
</div>


<% if @logs.any? %>
  <br>
  <hr class="style-two">
  <h2 class="mt-4">
    Activité
  </h2>
  <table id="logs">
    <%= render partial:'logs/log', collection: @logs, :day => 0 %>
  </table>
  <br>
  <% if @logs.count > 5 %>
    <small>
      <i>Liste des 5 derniers changements <%= link_to "Afficher tout", logs_path(project_id:@project.id), class:"link" %></i>
    </small>
    <br>
  <% end %>
<% end %>

<% if @comments.any? %>
  <br>
  <hr class="style-two">
  <h2 class="mt-4">
    Discussions
  </h2>
  <%= render partial:'comments/commentfull', collection:@comments, as: :comment, day:0  %>
  <br>
  <% if @project.comments.count > 5 %>
    <small><i>Liste des 5 derniers commentaires <%= link_to "Afficher tout", comments_path(project_id:@project.id) %></i></small>
    <br>
  <% end %>
<% end %>