config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  scope "/admin" do
    resources :users do
      member do
        get :icalendar
      end
    end
  end

  get "sitemap" => "sitemap#show", format: :xml, as: :sitemap

  get 'invite' => 'projects#invite' 
  post 'invite' => 'projects#invite_do' 
  get 'accepter' => 'projects#accepter' 

  post 'todos/:id/close' => 'todos#close'
  post 'todos/:id/reopen' => 'todos#reopen'

  get 'projects/:id/save_as_template' => 'projects#save_as_template'
  post 'projects/:id/save_as_template' => 'projects#save_as_template_post'

  get 'documents/index'
  delete 'documents/purge'

  get "agenda/index"

  get "show_attrs" => "tables#show_attrs" 

  resources :accounts, only: %i[ edit update ] do
    member do
      get :suppression_compte
      post :suppression_compte_do
    end
  end
  resources :comments, only: %i[ index create ]
  resources :templates
  resources :logs
  resources :todolists, except: :index
  resources :participants, only: %i[ edit update ]
  resources :todos, except: %i[ show ]
  resources :projects
  resources :tables
  resources :fields, only: %i[ edit update create destroy ]
  resources :mail_logs, only: %i[ index ]

  get 'tables/:id/fill' => 'tables#fill', as: :fill
  post 'tables/:id/fill' => 'tables#fill_do', as: :fill_do
  get 'tables/:id/link' => 'tables#link', as: :link
  post 'tables/:id/link' => 'tables#link_do', as: :link_do

  delete 'tables/:id/delete_record' => 'tables#delete_record', as: :delete_record

  get 'about', to: 'pages#about', as: :about
  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  get 'audits/index'

  get '/service-worker.js' => "service_worker#service_worker"
  get '/manifest.json' => "service_worker#manifest"

  namespace :api, defaults: {format: 'json'} do 
    namespace :v1 do 
        resources :todos
    end 
  end

  root 'projects#index'
end

app/models/account.rb
class Account < ApplicationRecord
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  audited

  has_many :projects, dependent: :destroy
  has_many :templates, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :tables, dependent: :destroy
  has_many :mail_logs, dependent: :destroy

  has_many :values, through: :tables
  has_many :participants, through: :projects
  has_many :todolists, through: :projects
  has_many :todos, through: :todolists
  has_many :comments, through: :users

  accepts_nested_attributes_for :users

  validates :name, presence: true, uniqueness: true

  after_create :account_notification

  # has_attached_file :logo, :styles => { :thumb => "60x60>" }, :default_url => "new_logo.png"
  # validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/
  
  private

  def slug_candidates
    [SecureRandom.uuid]
  end

  def account_notification
    Notifier.with(account: self).new_account_notification.deliver_now
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account
  before_action :user_authorized?

  # skip_before_action :authorize, except: [:edit, :update, :destroy, :index, :show]


  # GET /accounts/1/edit
  def edit
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to current_user, notice: 'Compte modifié.' }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  def suppression_compte
  end

  def suppression_compte_do
    Notifier.with(account: @account, reason: params[:reason]).delete_account_notification.deliver_now

    @account.destroy

    current_user = nil

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find_by(slug: params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def account_params
    params.require(:account).permit(:name, :password, :password_confirmation, :sitename, :logo, :hostname,
                                    users_attributes: %i[id email name username password password_confirmation])
  end

  def user_authorized?
    authorize @account
  end
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('errors.messages.not_saved', count: @account.errors.count) %></h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Nom du compte' %><br>
    <%= f.text_field :name %><br>
    <small><i>Veuillez nommer votre espace de projets. C'est dans cet espace que seront partagés les projets entre vous et les participants que vous inviterez.<br>
    Vous pouvez en avoir plusieurs, selon la nature de vos projets (Pro/Perso/etc.).</i></small>
  </div>

  <% unless @account.new_record? %>
    <div class="field">
      <%= f.label :hostname %><br>
      <%= f.text_field :hostname %><br>
    </div>
  <% end %>

  <% if @account.new_record? %>
    <%= f.fields_for :users do |users_form| %>
      <div class="field">
        <%= users_form.label :name, "Votre nom" %><br>
        <%= users_form.text_field :name %><br>
        <small><i>C'est le nom que verront les autres participants</i></small>
      </div>

      <div class="field">
        <%= users_form.label :username, "Votre identifiant" %><br>
        <%= users_form.text_field :username %><br>
        <small><i>Cet identifiant vous sera demandé à chaque connexion.<br> Faites court, si vous avez un pseudo, c'est le moment de l'utiliser ;-)</i></small>
      </div>

      <div class="field">
        <%= users_form.label :email, 'Courriel' %><br>
        <%= users_form.text_field :email %><br>
        <small><i>Indiquez l'adresse de messagerie qui recevra les notifications</i></small>
      </div>

      <div class="field">
        <%= users_form.label :password, 'Mot de passe' %><br>
        <%= users_form.password_field :password %><br>
      </div>  

      <div class="field">
        <%= users_form.label :password_confirmation, 'Confirmation' %><br>
        <%= users_form.password_field :password_confirmation %><br>
      </div>  

    <% end %>
    <br>
  <% end %>

  <div class="actions">
    <%= f.submit @account.new_record? ? 'Créer le compte' : 'Enregistrer', class: 'btn btn-primary btn-outline mt-4' %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1 class="mb-6">Modification de compte</h1>

<%= render 'form' %>

<%= link_to 'Retour', current_user %>

app/views/accounts/suppression_compte.html.erb
<div class="max-w-3xl mx-auto">
  <h1 class="text-error mb-8">
    Attention, vous êtes sur le point de supprimer définitivement votre espace de travail (<%= current_user.account.name %>) ainsi que tous ses participants !
  </h1>
  <p class="mb-2">Toutes les données ci-dessous seront détruites :</p>
  <ul>
    <li>- Projets (<%= current_user.account.projects.count %>)</li>
    <li>- Todolists / To-dos (<%= current_user.account.todos.count %>)</li>
    <li>- Documents (<%= current_user.account.todos.select { |todo| todo.document.attached? }.count %>)</li>
    <li>- Tables (<%= current_user.account.tables.count %>)</li>
    <li>- Activités (<%= current_user.account.projects.count %>)</li>
    <li>- Commentaires (<%= current_user.account.comments.count %>)</li>
    <li>- Et tout ce qui est lié, de près ou de loin, à votre espace de travail</li>
  </ul>
  <br>
  <p>Si le cœur vous en dit, vous pouvez nous en expliquer la raison ci-dessous :</p>
  <p>Vos commentaires nous permettrons d'améliorer le produit, merci :)</p>

  <%= form_with(url: suppression_compte_do_account_path) do |form| %>
    <%= form.text_area :reason, class:"textarea textarea-bordered w-full mb-8", placeholder: "Je peux expliquer ici la raison de mon départ" %>
    <%= link_to "Annuler", user_path(current_user), class: "btn btn-outline" %>
    <%= form.submit "Supprimer mon compte", class: "btn btn-error btn-outline", 'data-turbo-confirm': "ÊTES-VOUS BIEN SÛR DE VOULOIR SUPPRIMER VOTRE ESPACE DE TRAVAIL ? VOUS NE POURREZ PLUS REVENIR EN ARRIÈRE !!!"  %>
  <% end %>
</div>